### ISSUE TITLE
Bug affecting tree based mods

### ISSUE THREAD

**Issue by DilanRona** [Tubbles/Construction_Drones#11]
I picked up a problem where blueprints of saplings from tree based mods (simple saplings) would not grow.

Closer examination using the default Factorio construction drones, I noticed 2 events being called. The first being entity-ghost, and the second being the sapling placed.

Using your drones however only results in one event, entity-ghost. The second event the mod needs is not triggered.

The issue in question affects any mod that the construction bot replaces entity-ghosts, and does not call the second event.

**Comment by Tubbles** [comment]
Closing as 2.0 has made a lot of changes, so this might be fixed. If not, please open a new bug report with a save file where this issue is reproducible
