### ISSUE TITLE
Mod Conflict with HiveMind

### ISSUE THREAD

**Issue by theisen1337** [Tubbles/Construction_Drones#12]
Not sure if this bug breaks other multi-force mods. but this mod breaks collision for cliffs and creep while playing as biters in the HiveMind Mod. https://mods.factorio.com/mod/Hive_Mind_MitchPlay

**Comment by Tubbles** [comment]
Closing as 2.0 has made a lot of changes, so this might be fixed. If not, please open a new bug report with a save file where this issue is reproducible
