### ISSUE TITLE
if I place bioind solar farm it's solar productivity, if drone place them it's bio industries :)... and item deletion

### ISSUE THREAD

**Issue by angrypidgeon123** [Tubbles/Construction_Drones#14]
(https://github.com/RedRafe/solar-productivity/issues/7)

Also if construction drones place a packed box with items (it's a mod but not boxing or packing tape :), they delete its content. EDIT: the packing mod is picker inventory tools with > moveable chests option

Also if contruction drones place a Factorissimo notnotmelon factory they delete its content

There's also other issues along these lines. Just lost an astronomical sattelite (Space Exploration mod item) so I'm looking sideways at my construction drones hmm

EDIT: if I place a time tools mod (clock combinator) ghost, the combinator doesn't work as in count time

if I place stuff ghosts and still hold the item in the cursor, the drones will not launch to construct it until I cancel the item from cursor (like pressing q). 

personal roboport drones work in all these instances

**Comment by Tubbles** [comment]
Closing as 2.0 has made a lot of changes, so this might be fixed. If not, please open a new bug report with a save file where this issue is reproducible
