### ISSUE TITLE
Drone viberate around when building railway blueprint

### ISSUE THREAD

**Issue by Rugal** [Tubbles/Construction_Drones#21]
Thanks for the latest fix `2.0.1`, it does fixed many unrecoverable crash situation.    
It works fine for other blueprints and item upgrades, however, when I place an blueprint for 4 lane railways, all drones set out and vibrating around the intersection of railways, doing nothing. Even if there are many unplaced item.  
The weird thing is, few of drone would still place the item once in a while, but not always the case. I have to wait like 5 mins to see a drone to place one another tile of railway.  

![image](https://github.com/user-attachments/assets/c2032bb0-7e88-486a-a997-5cd9d4ebb07e)

Screenshot to illustrate drone stuck around the intersection of railways, I have 10 drones in inventory, but only 6 of them are here.

I didn't change the range of drone at all. Drone does not build even if I stand on the blueprint place.   
They will not come back to my inventory anymore.   I am not able to them back by right clicking easily, as they vibrating, right clicking won't be able to lock them.   

![image](https://github.com/user-attachments/assets/159e966b-ec8c-498e-95b0-bb32e1258738)

**Comment by Tubbles** [comment]
Thank you for this report! I will look into it, this seems less than optimal! :)

**Comment by Rugal** [comment]
![image](https://github.com/user-attachments/assets/5cc8ed13-a020-480a-8c6c-79b7409fa3e7)

Just tested, if without intersection, drone will work as expected.

**Comment by Rugal** [comment]
My observation is, drone seems treats railway as real entity that blocks the path finding, which eventually causes drone to vibrate and going nowhere.  

![image](https://github.com/user-attachments/assets/b0e67820-0943-472e-9939-cacb2fb610e8)

**Comment by Tubbles** [comment]
Fixed in 04eb8bd
