### ISSUE TITLE
Crash when drone try placing belt next to a belt balancer

### ISSUE THREAD

**Issue by GatDoo** [Tubbles/Construction_Drones#22]
![crash](https://github.com/user-attachments/assets/0564295d-2a03-4403-8cd9-921ff5379cf7)

Also, drone can't go throught belt !

**Comment by Tubbles** [comment]
Thank you for this bug report! To aid the hunting please add the following:

* [factorio-current.log](https://wiki.factorio.com/Log_file)
* A general description of how the bug happened
* Any error messages
* If possible, consider uploading a save file where the bug is reproducible

**Comment by GatDoo** [comment]
[factorio-current.log](https://github.com/user-attachments/files/17562515/factorio-current.log)
[DLC Modded[item=express-transport-belt].zip](https://github.com/user-attachments/files/17562530/DLC.Modded.item.express-transport-belt.zip)

**Comment by Tubbles** [comment]
I will try to look at this for v2.0.3 release

**Comment by Tubbles** [comment]
It looks like the error is not caused by Updated Construction Drones, please reach out to the developer of the belt-balancer-2 mod!
