### ISSUE TITLE
Invalid item ID causing unrecoverable error

### ISSUE THREAD

**Issue by jhtrzcinski** [Tubbles/Construction_Drones#23]
![image](https://github.com/user-attachments/assets/11367780-0eb1-4a9e-9223-2976deedca7b)

These are the mods it was in a save with that might have the invalid item; likely Pipe Plus since I haven't made it to nuclear energy in the game yet.

![image](https://github.com/user-attachments/assets/6dcbda65-4064-42e3-84fb-d738836687bc)

**Comment by Tubbles** [comment]
Hello, I've recently fixed this crash in 2.0.3 :)
